from django.conf.urls.defaults import *

urlpatterns = patterns('jetpack.views',
	url(r'^gallery/$', 'gallery', name='gallery'),
	# Jetpacks
    url(r'^jp_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/$',
		'jetpack_version_edit', name='jp_jetpack_version_edit'),
	url(r'^jp_(?P<slug>.*)/version_create/$', 
		'jetpack_version_create', name='jp_jetpack_version_create'),
	url(r'^jp_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/update/$', 
		'jetpack_version_update', name='jp_jetpack_version_update'),
	url(r'^jp_(?P<slug>.*)/update/$', 
		'item_update', {"type": "jetpack"}, name='jp_jetpack_update'),
	url(r'^jp_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/add_dependency/$',
		'add_dependency', {'type': 'jetpack'}, name='jp_jetpack_add_dependency'),
	url(r'^jp_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/save_as_base/$', 
		'jetpack_version_save_as_base', name='jp_jetpack_version_save_as_base'),
	url(r'^jp/create',
		'item_create', {"type": "jetpack"}, name='jp_jetpack_create'),
    url(r'^jp_(?P<slug>.*)/$',
		'jetpack_edit', name='jp_jetpack_edit'),
	# Capabilities
    url(r'^mod_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/$',
		'capability_version_edit', name='jp_capability_version_edit'),
	url(r'^mod_(?P<slug>.*)/version_create/$', 
		'capability_version_create', name='jp_capability_version_create'),
	url(r'^mod_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/update/$', 
		'capability_version_update', name='jp_capability_version_update'),
	url(r'^mod_(?P<slug>.*)/update/$', 
		'item_update', {"type": "capability"}, name='jp_capability_update'),
	url(r'^mod_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/add_dependency/$',
		'add_dependency', {'type': 'capability'}, name='jp_capability_add_dependency'),
	url(r'^mod_(?P<slug>.*)/v_(?P<version>.*)\.(?P<counter>\d+)/save_as_base/$', 
		'capability_version_save_as_base', name='jp_capability_version_save_as_base'),
	url(r'^cap/create',
		'item_create', {"type": "capability"},  name='jp_capability_create'),
    url(r'^mod_(?P<slug>.*)/$',
		'capability_edit', name='jp_capability_edit'),
)

